services:
  proxy:
    image: "nginx:alpine3.18"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    entrypoint: "nginx -g 'daemon off;'"
    restart: always
  gama-server:
    build:
      context: .
      dockerfile: ./docker/gama-server/Dockerfile
    volumes:
      - ./pig-farm:/pig-farm
    ports:
      - "6868:6868"
    restart: always
  api:
    depends_on:
      - gama-server
      - proxy
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./pig-farm:/app/pig-farm
    ports:
      - "8000:8000"
    restart: always